### ISSUE TITLE
Unstated dependency on jQuery

### ISSUE THREAD

**Issue by stuartm** [clippings/layout-grid#25]
The jQuery dependency isn't mentioned anywhere, either in the README or in the installation notes.

On a very personal note, it's a disappointing requirement given the claim that only "a little bit of javascript." is required.

**Comment by hkdobrev** [comment]
The dependency on jQuery is very clearly stated in the `package.json` file which is used when installing dependencies.

Feel free to submit a pull request if you want to state it more clearly than that.
