### ISSUE TITLE
Dropping does nothing on IE11

### ISSUE THREAD

**Issue by thomashub** [clippings/layout-grid#7]
Trying your demo (https://clippings.github.io/layout-grid/) in IE11 (Windows 10), I can pick up elements, and it shows me dragging them around, but dropping them somewhere has no effect. Since your page mentions that it should work in IE, I thought I'd report this.

It does work in MS Edge.

**Comment by ivank** [comment]
Yeah there was a small bug - it should be working properly now - can you check?

**Comment by thomashub** [comment]
Confirmed working. :+1: 

The cursor does continually quickly flash between the normal and the dragging cursors while dragging, but that doesn't impair functionality.
